probeType       8                       # atom type of ProbeParticle (to choose L-J potential ),e.g. 8 for CO, 54 for Xe
charge         -0.05                    # effective charge of probe particle [e]
klat            0.15                     # [N/m] harmonic spring potential (x,y) components, x,y is bending stiffnes
krad            20.00                   # [N/m] harmonic spring potential R component, R is the particle-tip bond-length stiffnes
r0Probe         0.0 0.0  3.00           # [Å] equilibirum position of probe particle (x,y,R) components, R is bond length, x,y introduce tip asymmetry

tip     dz2
PBC             True                    # Periodic boundary conditions ? [ True/False ]
# gridA       22.5531100000000002  0.00000  0.00000    # a-vector of unit cell; recommended format (x,y,0)
# gridB       0.00000   24.6346510000000016  0.00000    # b-vector of unit cell; recommended format (x,y,0)
# gridC        0.000   0.0000 35.8228650000000002 # c-vector of unit cell; recommended format (0,0,z)
# scanMin      0.0    0.0     4.50         # start of scanning (x,y,z)
# scanMax     20.0   20.0    12.50         # end of scanning (x,y,z)
scanMin      0.0    0.0     9.00
scanMax     22.954756   25.067562    21.50
# scanMax    28.746418 30.067187  25.50






scanStep 0.1 0.1 0.01

Amplitude       1.0                     # [Å] oscillation amplitude for conversion Fz->df
# scanMax 12.798 12.798 14.0
# plotSliceFrom 1010
# plotSliceTo   1110